# Generated by Django 4.0.5 on 2022-07-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userContactNumber', models.IntegerField()),
                ('userAge', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
