# Generated by Django 4.0.5 on 2022-07-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0003_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
