# Generated by Django 4.0.5 on 2022-07-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='updatedAt',
        ),
    ]
