# Generated by Django 4.0.5 on 2022-07-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0006_remove_userdetail_createdat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
