# Generated by Django 4.0.5 on 2022-07-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapplication', '0007_delete_userdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userContactNumber', models.IntegerField()),
                ('userAge', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
