# Generated by Django 4.0.5 on 2022-07-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=255)),
                ('brandName', models.CharField(max_length=255)),
                ('offer', models.IntegerField()),
                ('quantityLeft', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imageURL', models.URLField()),
            ],
        ),
    ]
