# Generated by Django 4.0.5 on 2022-07-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapplication', '0011_alter_productdetails_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='imageURL',
            field=models.CharField(max_length=100000),
        ),
    ]
